export interface CampusEntry {
  name: string;
  type: 'University' | 'TVET' | 'KMTC' | 'TTC' | 'College';
  county: string;
}

export const KENYA_CAMPUSES: CampusEntry[] = [
  // ── Public Universities ──────────────────────────────────────────────────
  { name: 'University of Nairobi - Main Campus', type: 'University', county: 'Nairobi' },
  { name: 'University of Nairobi - Parklands', type: 'University', county: 'Nairobi' },
  { name: 'University of Nairobi - Upper Kabete', type: 'University', county: 'Nairobi' },
  { name: 'Kenyatta University - Main Campus', type: 'University', county: 'Nairobi' },
  { name: 'Kenyatta University - CBD Campus', type: 'University', county: 'Nairobi' },
  { name: 'JKUAT - Main Campus (Juja)', type: 'University', county: 'Kiambu' },
  { name: 'JKUAT - Karen Campus', type: 'University', county: 'Nairobi' },
  { name: 'JKUAT - Westlands Campus', type: 'University', county: 'Nairobi' },
  { name: 'JKUAT - CBD Campus', type: 'University', county: 'Nairobi' },
  { name: 'Moi University - Main Campus (Eldoret)', type: 'University', county: 'Uasin Gishu' },
  { name: 'Moi University - Town Campus', type: 'University', county: 'Uasin Gishu' },
  { name: 'Egerton University - Main Campus', type: 'University', county: 'Nakuru' },
  { name: 'Egerton University - Nairobi CBD', type: 'University', county: 'Nairobi' },
  { name: 'Maseno University', type: 'University', county: 'Kisumu' },
  { name: 'Maseno University - Kisumu CBD', type: 'University', county: 'Kisumu' },
  { name: 'Masinde Muliro University', type: 'University', county: 'Kakamega' },
  { name: 'Jaramogi Oginga Odinga University', type: 'University', county: 'Siaya' },
  { name: 'South Eastern Kenya University', type: 'University', county: 'Kitui' },
  { name: 'Dedan Kimathi University', type: 'University', county: 'Nyeri' },
  { name: 'Laikipia University', type: 'University', county: 'Laikipia' },
  { name: 'Murang\'a University of Technology', type: 'University', county: 'Murang\'a' },
  { name: 'Chuka University', type: 'University', county: 'Tharaka Nithi' },
  { name: 'Tharaka University', type: 'University', county: 'Tharaka Nithi' },
  { name: 'University of Embu', type: 'University', county: 'Embu' },
  { name: 'Kisii University', type: 'University', county: 'Kisii' },
  { name: 'Rongo University', type: 'University', county: 'Migori' },
  { name: 'Garissa University', type: 'University', county: 'Garissa' },
  { name: 'Pwani University', type: 'University', county: 'Kilifi' },
  { name: 'Technical University of Mombasa', type: 'University', county: 'Mombasa' },
  { name: 'Technical University of Kenya - Main (Nairobi)', type: 'University', county: 'Nairobi' },
  { name: 'Karatina University', type: 'University', county: 'Nyeri' },
  { name: 'Kirinyaga University', type: 'University', county: 'Kirinyaga' },
  { name: 'University of Eldoret', type: 'University', county: 'Uasin Gishu' },
  { name: 'Multimedia University of Kenya', type: 'University', county: 'Nairobi' },
  { name: 'Co-operative University of Kenya', type: 'University', county: 'Nairobi' },

  // ── Private Universities ─────────────────────────────────────────────────
  { name: 'Strathmore University', type: 'University', county: 'Nairobi' },
  { name: 'USIU-Africa (United States International University)', type: 'University', county: 'Nairobi' },
  { name: 'Daystar University - Nairobi', type: 'University', county: 'Nairobi' },
  { name: 'Daystar University - Athi River', type: 'University', county: 'Machakos' },
  { name: 'Africa Nazarene University', type: 'University', county: 'Nairobi' },
  { name: 'Catholic University of Eastern Africa (CUEA)', type: 'University', county: 'Nairobi' },
  { name: 'St. Paul\'s University (Limuru)', type: 'University', county: 'Kiambu' },
  { name: 'Kabarak University', type: 'University', county: 'Nakuru' },
  { name: 'Adventist University of Africa', type: 'University', county: 'Nairobi' },
  { name: 'KCA University', type: 'University', county: 'Nairobi' },
  { name: 'Zetech University - Ruiru', type: 'University', county: 'Kiambu' },
  { name: 'Zetech University - Nairobi Town', type: 'University', county: 'Nairobi' },
  { name: 'Mount Kenya University - Thika', type: 'University', county: 'Kiambu' },
  { name: 'Mount Kenya University - Nairobi CBD', type: 'University', county: 'Nairobi' },
  { name: 'Mount Kenya University - Mombasa', type: 'University', county: 'Mombasa' },
  { name: 'Mount Kenya University - Nakuru', type: 'University', county: 'Nakuru' },
  { name: 'Mount Kenya University - Eldoret', type: 'University', county: 'Uasin Gishu' },
  { name: 'University of Africa (Eldoret)', type: 'University', county: 'Uasin Gishu' },
  { name: 'Pan Africa Christian University', type: 'University', county: 'Nairobi' },
  { name: 'Jomo Kenyatta University - Kisumu Campus', type: 'University', county: 'Kisumu' },
  { name: 'Scott Christian University', type: 'University', county: 'Machakos' },
  { name: 'Aga Khan University', type: 'University', county: 'Nairobi' },
  { name: 'Great Lakes University of Kisumu', type: 'University', county: 'Kisumu' },
  { name: 'University of Eastern Africa Baraton', type: 'University', county: 'Uasin Gishu' },

  // ── National Polytechnics / TU Kenya campuses ────────────────────────────
  { name: 'TU Kenya - Nairobi Main', type: 'TVET', county: 'Nairobi' },
  { name: 'TU Kenya - Mombasa Polytechnic', type: 'TVET', county: 'Mombasa' },
  { name: 'TU Kenya - Kisumu Polytechnic', type: 'TVET', county: 'Kisumu' },
  { name: 'Kenya Institute of Management (KIM)', type: 'TVET', county: 'Nairobi' },
  { name: 'Kenya School of Government', type: 'TVET', county: 'Nairobi' },

  // ── TVET Institutions ────────────────────────────────────────────────────
  { name: 'Nairobi Technical Training Institute (NTTI)', type: 'TVET', county: 'Nairobi' },
  { name: 'Kenya Technical Trainers College', type: 'TVET', county: 'Nairobi' },
  { name: 'Kabete National Polytechnic', type: 'TVET', county: 'Nairobi' },
  { name: 'Kenya Coast National Polytechnic', type: 'TVET', county: 'Mombasa' },
  { name: 'Rift Valley Institute of Science & Technology', type: 'TVET', county: 'Nakuru' },
  { name: 'Sigalagala National Polytechnic', type: 'TVET', county: 'Kakamega' },
  { name: 'Mombasa Technical Training Institute', type: 'TVET', county: 'Mombasa' },
  { name: 'Kitale National Polytechnic', type: 'TVET', county: 'Trans Nzoia' },
  { name: 'Eldoret Polytechnic', type: 'TVET', county: 'Uasin Gishu' },
  { name: 'Kisumu Polytechnic', type: 'TVET', county: 'Kisumu' },
  { name: 'Thika Technical Training Institute', type: 'TVET', county: 'Kiambu' },
  { name: 'Nyeri National Polytechnic', type: 'TVET', county: 'Nyeri' },
  { name: 'Nakuru Technical Training Institute', type: 'TVET', county: 'Nakuru' },
  { name: 'Machakos Institute of Technology', type: 'TVET', county: 'Machakos' },
  { name: 'Kisii National Polytechnic', type: 'TVET', county: 'Kisii' },
  { name: 'Kakamega Technical & Vocational College', type: 'TVET', county: 'Kakamega' },
  { name: 'Meru National Polytechnic', type: 'TVET', county: 'Meru' },
  { name: 'Embu National Polytechnic', type: 'TVET', county: 'Embu' },
  { name: 'Garissa Technical Training Institute', type: 'TVET', county: 'Garissa' },
  { name: 'Kilifi Technical Training Institute', type: 'TVET', county: 'Kilifi' },
  { name: 'Kwale Technical & Vocational College', type: 'TVET', county: 'Kwale' },
  { name: 'Bungoma Technical Training Institute', type: 'TVET', county: 'Bungoma' },
  { name: 'Vihiga Technical Training Institute', type: 'TVET', county: 'Vihiga' },
  { name: 'Siaya Institute of Technology', type: 'TVET', county: 'Siaya' },
  { name: 'Homa Bay Technical Training Institute', type: 'TVET', county: 'Homa Bay' },
  { name: 'Migori Technical Training Institute', type: 'TVET', county: 'Migori' },
  { name: 'Narok Technical Training Institute', type: 'TVET', county: 'Narok' },
  { name: 'Kajiado Technical Institute for Business', type: 'TVET', county: 'Kajiado' },
  { name: 'Kericho Technical Training Institute', type: 'TVET', county: 'Kericho' },
  { name: 'Nandi Technical Training Institute', type: 'TVET', county: 'Nandi' },
  { name: 'Bomet Technical Training Institute', type: 'TVET', county: 'Bomet' },
  { name: 'Elgeyo Marakwet Technical', type: 'TVET', county: 'Elgeyo Marakwet' },
  { name: 'Baringo Technical College', type: 'TVET', county: 'Baringo' },
  { name: 'Laikipia Technical Training Institute', type: 'TVET', county: 'Laikipia' },
  { name: 'Nyahururu Technical Training Institute', type: 'TVET', county: 'Laikipia' },
  { name: 'Nyamira Technical Training Institute', type: 'TVET', county: 'Nyamira' },
  { name: 'Tharaka Nithi Technical', type: 'TVET', county: 'Tharaka Nithi' },
  { name: 'Isiolo Technical Training Institute', type: 'TVET', county: 'Isiolo' },
  { name: 'Marsabit Technical Training Institute', type: 'TVET', county: 'Marsabit' },
  { name: 'Mandera Technical Training Institute', type: 'TVET', county: 'Mandera' },
  { name: 'Wajir Technical Training Institute', type: 'TVET', county: 'Wajir' },
  { name: 'Turkana Technical Training Institute', type: 'TVET', county: 'Turkana' },
  { name: 'West Pokot Technical Training Institute', type: 'TVET', county: 'West Pokot' },
  { name: 'Samburu Technical Training Institute', type: 'TVET', county: 'Samburu' },
  { name: 'Lamu Technical Training Institute', type: 'TVET', county: 'Lamu' },
  { name: 'Tana River Technical Training Institute', type: 'TVET', county: 'Tana River' },
  { name: 'Taita Taveta University College', type: 'TVET', county: 'Taita Taveta' },

  // ── KMTC Campuses ────────────────────────────────────────────────────────
  { name: 'KMTC - Nairobi (Main)', type: 'KMTC', county: 'Nairobi' },
  { name: 'KMTC - Mombasa', type: 'KMTC', county: 'Mombasa' },
  { name: 'KMTC - Kisumu', type: 'KMTC', county: 'Kisumu' },
  { name: 'KMTC - Eldoret', type: 'KMTC', county: 'Uasin Gishu' },
  { name: 'KMTC - Nakuru', type: 'KMTC', county: 'Nakuru' },
  { name: 'KMTC - Nyeri', type: 'KMTC', county: 'Nyeri' },
  { name: 'KMTC - Kakamega', type: 'KMTC', county: 'Kakamega' },
  { name: 'KMTC - Meru', type: 'KMTC', county: 'Meru' },
  { name: 'KMTC - Embu', type: 'KMTC', county: 'Embu' },
  { name: 'KMTC - Kisii', type: 'KMTC', county: 'Kisii' },
  { name: 'KMTC - Thika', type: 'KMTC', county: 'Kiambu' },
  { name: 'KMTC - Machakos', type: 'KMTC', county: 'Machakos' },
  { name: 'KMTC - Kitale', type: 'KMTC', county: 'Trans Nzoia' },
  { name: 'KMTC - Homabay', type: 'KMTC', county: 'Homa Bay' },
  { name: 'KMTC - Migori', type: 'KMTC', county: 'Migori' },
  { name: 'KMTC - Garissa', type: 'KMTC', county: 'Garissa' },
  { name: 'KMTC - Kilifi', type: 'KMTC', county: 'Kilifi' },
  { name: 'KMTC - Voi', type: 'KMTC', county: 'Taita Taveta' },
  { name: 'KMTC - Kericho', type: 'KMTC', county: 'Kericho' },
  { name: 'KMTC - Siaya', type: 'KMTC', county: 'Siaya' },
  { name: 'KMTC - Bungoma', type: 'KMTC', county: 'Bungoma' },
  { name: 'KMTC - Muranga', type: 'KMTC', county: 'Murang\'a' },
  { name: 'KMTC - Karatina', type: 'KMTC', county: 'Nyeri' },
  { name: 'KMTC - Kitui', type: 'KMTC', county: 'Kitui' },
  { name: 'KMTC - Isiolo', type: 'KMTC', county: 'Isiolo' },
  { name: 'KMTC - Wajir', type: 'KMTC', county: 'Wajir' },
  { name: 'KMTC - Mandera', type: 'KMTC', county: 'Mandera' },
  { name: 'KMTC - Turkana', type: 'KMTC', county: 'Turkana' },
  { name: 'KMTC - Marsabit', type: 'KMTC', county: 'Marsabit' },
  { name: 'KMTC - Kajiado', type: 'KMTC', county: 'Kajiado' },
  { name: 'KMTC - Narok', type: 'KMTC', county: 'Narok' },
  { name: 'KMTC - Bomet', type: 'KMTC', county: 'Bomet' },
  { name: 'KMTC - Nandi Hills', type: 'KMTC', county: 'Nandi' },
  { name: 'KMTC - Baringo', type: 'KMTC', county: 'Baringo' },
  { name: 'KMTC - Nyamira', type: 'KMTC', county: 'Nyamira' },
  { name: 'KMTC - Lamu', type: 'KMTC', county: 'Lamu' },

  // ── Teacher Training Colleges ────────────────────────────────────────────
  { name: 'Kenya Technical Trainers College (KTTC)', type: 'TTC', county: 'Nairobi' },
  { name: 'Kagumo Teachers Training College', type: 'TTC', county: 'Nyeri' },
  { name: 'Shanzu Teachers Training College', type: 'TTC', county: 'Mombasa' },
  { name: 'Mosoriot Teachers Training College', type: 'TTC', county: 'Nandi' },
  { name: 'Koilege Teachers Training College', type: 'TTC', county: 'Baringo' },
  { name: 'Garba Tula Teachers Training College', type: 'TTC', county: 'Isiolo' },
  { name: 'Highridge Teachers Training College', type: 'TTC', county: 'Nairobi' },
  { name: 'Nairobi Primary Teachers College', type: 'TTC', county: 'Nairobi' },
  { name: 'Eldoret Teachers Training College', type: 'TTC', county: 'Uasin Gishu' },
  { name: 'Mombasa Teachers Training College', type: 'TTC', county: 'Mombasa' },
  { name: 'Kisumu Teachers Training College', type: 'TTC', county: 'Kisumu' },
  { name: 'Machakos Teachers Training College', type: 'TTC', county: 'Machakos' },
  { name: 'Muranga Teachers College', type: 'TTC', county: 'Murang\'a' },
  { name: 'Kamwenja Teachers Training College', type: 'TTC', county: 'Nyeri' },

  // ── Private Colleges ─────────────────────────────────────────────────────
  { name: 'Kenya College of Accountancy (KCA)', type: 'College', county: 'Nairobi' },
  { name: 'Nairobi Institute of Technology', type: 'College', county: 'Nairobi' },
  { name: 'Institute of Advanced Technology (IAT)', type: 'College', county: 'Nairobi' },
  { name: 'Kenya College of Communication Technology', type: 'College', county: 'Nairobi' },
  { name: 'East Africa Institute of Certified Studies (EAICS)', type: 'College', county: 'Nairobi' },
  { name: 'Nairobi Aviation College', type: 'College', county: 'Nairobi' },
  { name: 'Kenya Utalii College', type: 'College', county: 'Nairobi' },
  { name: 'Kiriri Women\'s University', type: 'College', county: 'Nairobi' },
  { name: 'Management University of Africa', type: 'College', county: 'Nairobi' },
  { name: 'Pioneer International University', type: 'College', county: 'Nairobi' },
  { name: 'NIBS College', type: 'College', county: 'Nairobi' },
  { name: 'East Africa School of Management', type: 'College', county: 'Nairobi' },
  { name: 'Buruburu Institute of Fine Arts', type: 'College', county: 'Nairobi' },
  { name: 'Kenya Institute of Mass Communication (KIMC)', type: 'College', county: 'Nairobi' },
  { name: 'Consolata School of Nursing', type: 'College', county: 'Nairobi' },
  { name: 'AMREF International University', type: 'University', county: 'Nairobi' },
  { name: 'African Institute for Health and Development', type: 'College', county: 'Nairobi' },
  { name: 'Mombasa College of Hospitality', type: 'College', county: 'Mombasa' },
  { name: 'The Cooperative University of Kenya', type: 'University', county: 'Nairobi' },
  { name: 'Wanga University', type: 'University', county: 'Kakamega' },
  { name: 'Kabianga University', type: 'University', county: 'Kericho' },
];

export const CAMPUS_NAMES = KENYA_CAMPUSES.map(c => c.name);

export const TYPE_EMOJI: Record<string, string> = {
  University: '🎓',
  TVET:       '🔧',
  KMTC:       '🏥',
  TTC:        '📐',
  College:    '📖',
};
